server:
  port: 9095

management:
  server:
    port: 9096  
  endpoints:
    web:
      exposure:
        include: logfile
  endpoint:
    logfile:
      enabled: true
      external-file: app.log        

spring:
  main:
    headless: false
  datasource:
    url: jdbc:postgresql://192.168.178.73:5432/total_battle_db
    username: application
    password: testing123
    driver-class-name: org.postgresql.Driver    
  jpa:
    hibernate:
      ddl-auto: validate   # use validate if table already exists
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false    

logging:
  file:
    name: app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: INFO