package org.palermo.totalbattle.dao;

import org.palermo.totalbattle.entity.ProcessedImage;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class OcrDao {

    private static final String JDBC_URL = "jdbc:h2:file:./database;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    public OcrDao() {
        createTable();
    }

    private void createTable() {
        try (Connection conn = DriverManager.getConnection(JDBC_URL, USER, PASSWORD);
             Statement stmt = conn.createStatement()) {

            String sql = """
                CREATE TABLE IF NOT EXISTS OCR (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    WIDTH INT NOT NULL,
                    HEIGHT INT NOT NULL,
                    IMAGE BLOB NOT NULL,
                    STRING_VALUE VARCHAR,
                    CHARSET VARCHAR
                )
                """;

            stmt.execute(sql);

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void persist(BufferedImage image, String stringValue, String charset) {
        String sql = "INSERT INTO OCR (WIDTH, HEIGHT, IMAGE, STRING_VALUE, CHARSET) VALUES (?, ?, ?, ?, ?)";
        try (Connection conn = DriverManager.getConnection(JDBC_URL, USER, PASSWORD);
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, image.getWidth());
            ps.setInt(2, image.getHeight());
            ps.setBytes(3, toBytes(image));
            ps.setString(4, stringValue);
            ps.setString(5, charset);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public byte[] toBytes(BufferedImage image) {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            ImageIO.write(image, "png", baos); // format = "png", "jpg", etc.
            baos.flush();
            return baos.toByteArray();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public List<ProcessedImage> retrieve(int width, int height, String charSet) {

        List<ProcessedImage> list = new ArrayList<>();
        
        String sql = "SELECT IMAGE, STRING_VALUE FROM OCR WHERE WIDTH = ? AND HEIGHT = ? and CHARSET = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, width);
            ps.setInt(2, height);
            ps.setString(3, charSet);
            try(ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    byte[] bytes = rs.getBytes(1);
                    try(ByteArrayInputStream bais = new ByteArrayInputStream(bytes)) {
                        list.add(ProcessedImage.builder()
                                .image(ImageIO.read(bais))
                                .text(rs.getString(2))
                                .build());
                    }
                }
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return list;
    }
    
    private Connection getConnection() {
        try {
            return DriverManager.getConnection(JDBC_URL, USER, PASSWORD);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
