package org.palermo.totalbattle.player;

public enum Scenario {

    BONUS_SALES_FREE,
    TRAIN_TROOPS,
    QUESTS_TRY_FULL_CHESTS,
    SUMMONING_CIRCLE_COMMON_CAPTAIN_FRAGMENT,
    SUMMONING_CIRCLE_ELITE_CAPTAIN_FRAGMENT,
    SUMMONING_CIRCLE_ARTIFACT_FRAGMENT,
    SET_DEFAULT_CAPTAINS
}
